export const COUNTRY_LIST = [
  { code: 'US', name: 'United States', dial: '+1' },
  { code: 'GB', name: 'United Kingdom', dial: '+44' },
  { code: 'CA', name: 'Canada', dial: '+1' },
  { code: 'AU', name: 'Australia', dial: '+61' },
  { code: 'DE', name: 'Germany', dial: '+49' },
  { code: 'FR', name: 'France', dial: '+33' },
  { code: 'UA', name: 'Ukraine', dial: '+380' },
  { code: 'AE', name: 'United Arab Emirates', dial: '+971' },
  { code: 'NL', name: 'Netherlands', dial: '+31' },
  { code: 'ES', name: 'Spain', dial: '+34' },
  { code: 'IT', name: 'Italy', dial: '+39' },
  { code: 'CH', name: 'Switzerland', dial: '+41' },
  { code: 'SE', name: 'Sweden', dial: '+46' },
  { code: 'NO', name: 'Norway', dial: '+47' },
  { code: 'DK', name: 'Denmark', dial: '+45' },
  { code: 'FI', name: 'Finland', dial: '+358' },
  { code: 'PL', name: 'Poland', dial: '+48' },
  { code: 'IE', name: 'Ireland', dial: '+353' },
  { code: 'SG', name: 'Singapore', dial: '+65' },
  { code: 'JP', name: 'Japan', dial: '+81' },
  { code: 'KR', name: 'South Korea', dial: '+82' },
  { code: 'CN', name: 'China', dial: '+86' },
  { code: 'IN', name: 'India', dial: '+91' },
  { code: 'BR', name: 'Brazil', dial: '+55' },
  { code: 'MX', name: 'Mexico', dial: '+52' },
  { code: 'ZA', name: 'South Africa', dial: '+27' },
  { code: 'NZ', name: 'New Zealand', dial: '+64' },
  { code: 'AT', name: 'Austria', dial: '+43' },
  { code: 'BE', name: 'Belgium', dial: '+32' },
  { code: 'PT', name: 'Portugal', dial: '+351' },
  { code: 'IL', name: 'Israel', dial: '+972' },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966' },
  { code: 'TR', name: 'Turkey', dial: '+90' },
  { code: 'GR', name: 'Greece', dial: '+30' },
  { code: 'CZ', name: 'Czech Republic', dial: '+420' },
  { code: 'RO', name: 'Romania', dial: '+40' },
  { code: 'HU', name: 'Hungary', dial: '+36' },
  { code: 'AR', name: 'Argentina', dial: '+54' },
  { code: 'CL', name: 'Chile', dial: '+56' },
  { code: 'CO', name: 'Colombia', dial: '+57' },
  { code: 'PE', name: 'Peru', dial: '+51' },
  { code: 'PH', name: 'Philippines', dial: '+63' },
  { code: 'TH', name: 'Thailand', dial: '+66' },
  { code: 'VN', name: 'Vietnam', dial: '+84' },
  { code: 'MY', name: 'Malaysia', dial: '+60' },
  { code: 'ID', name: 'Indonesia', dial: '+62' },
  { code: 'EG', name: 'Egypt', dial: '+20' },
  { code: 'NG', name: 'Nigeria', dial: '+234' },
  { code: 'KE', name: 'Kenya', dial: '+254' },
  { code: 'PK', name: 'Pakistan', dial: '+92' },
  { code: 'BD', name: 'Bangladesh', dial: '+880' },
  { code: 'RS', name: 'Serbia', dial: '+381' },
  { code: 'HR', name: 'Croatia', dial: '+385' },
  { code: 'BG', name: 'Bulgaria', dial: '+359' },
  { code: 'SK', name: 'Slovakia', dial: '+421' },
  { code: 'SI', name: 'Slovenia', dial: '+386' },
  { code: 'LT', name: 'Lithuania', dial: '+370' },
  { code: 'LV', name: 'Latvia', dial: '+371' },
  { code: 'EE', name: 'Estonia', dial: '+372' },
  { code: 'CY', name: 'Cyprus', dial: '+357' },
  { code: 'MT', name: 'Malta', dial: '+356' },
  { code: 'LU', name: 'Luxembourg', dial: '+352' },
  { code: 'IS', name: 'Iceland', dial: '+354' },
];

export function getCountryByCode(code) {
  if (!code) return null;
  const upper = String(code).toUpperCase().trim();
  return COUNTRY_LIST.find((c) => c.code === upper) || null;
}

export function getCountryByName(name) {
  if (!name) return null;
  const lower = String(name).toLowerCase().trim();
  return COUNTRY_LIST.find((c) => c.name.toLowerCase() === lower) || null;
}
