// Curated Theme Layout Presets and Professional Color Palettes
// Built for Codex Dynamics Site Studio with surgical precision

export const THEME_LAYOUT_PRESETS = [
  // ── Dark Themes (16 Presets) ─────────────────────────────────────────────
  {
    id: 'codex-gold',
    name: 'Codex Pro Gold',
    badge: 'Agency Default',
    category: 'luxury',
    desc: 'High-impact dark luxury agency aesthetic with cinematic streamer video reel, floating island nav, and gold accents.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'highlights', 'services', 'portfolio', 'results', 'about', 'blog', 'reviews', 'contact'],
    primary: '#F0B90B',
    secondary: '#1E2329',
    accent: '#F0B90B',
    bg: '#0F1216',
    card: '#181A20',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Clean 6px', 'Glass Cards'],
  },
  {
    id: 'pacific-enterprise',
    name: 'Pacific Tech Enterprise',
    badge: 'SaaS & CRM',
    category: 'enterprise',
    desc: 'Technical enterprise blueprint layout with 50/50 split media hero, sticky header, sharp geometry, and cyan-blue data lines.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#2979F0',
    secondary: '#162235',
    accent: '#00D2FF',
    bg: '#0B111A',
    card: '#121D2C',
    layoutTags: ['Split 50/50', 'Sticky Top', 'Sharp 0px', 'Bordered'],
  },
  {
    id: 'emerald-mint',
    name: 'Emerald Peak Studio',
    badge: 'Creative Atelier',
    category: 'creative',
    desc: 'Avant-garde digital studio showcasing centered typographic focus, minimal top bar, modern rounded corners, and mint glow.',
    isLight: false,
    heroLayout: 'centered',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'reviews', 'results', 'blog', 'contact'],
    primary: '#0ECB81',
    secondary: '#132820',
    accent: '#0ECB81',
    bg: '#0A1510',
    card: '#10221A',
    layoutTags: ['Centered Focus', 'Minimal Nav', 'Modern 12px', 'Glass Cards'],
  },
  {
    id: 'royal-violet',
    name: 'Royal Violet Luxury',
    badge: 'Editorial & Luxury',
    category: 'luxury',
    desc: 'Bento-style layout with elegant serif headings, detached floating nav, and deep violet/amethyst card illumination.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#8B5CF6',
    secondary: '#241B3B',
    accent: '#A78BFA',
    bg: '#100C1B',
    card: '#1A142D',
    layoutTags: ['Bento Grid', 'Floating Island', 'Modern 12px', 'Editorial Serif'],
  },
  {
    id: 'crimson-amber',
    name: 'Crimson Kinetic High-ROAS',
    badge: 'Performance',
    category: 'performance',
    desc: 'High-energy conversion engine with sticky header, elevated contrast surfaces, and energetic scarlet-amber highlights.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'results', 'services', 'highlights', 'portfolio', 'reviews', 'contact', 'about', 'blog'],
    primary: '#F6465D',
    secondary: '#2E151B',
    accent: '#FF6B81',
    bg: '#16090D',
    card: '#240F15',
    layoutTags: ['Streamer Reel', 'Sticky Header', 'Clean 6px', 'Elevated Shadow'],
  },
  {
    id: 'dark-obsidian',
    name: 'Dark Obsidian Architectural',
    badge: 'Stealth Architectural',
    category: 'architectural',
    desc: 'Monochromatic architectural precision with bento cards, minimal clean border lines, and jet monospace typography.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'about', 'results', 'blog', 'reviews', 'contact'],
    primary: '#EAECEF',
    secondary: '#2B313A',
    accent: '#F0B90B',
    bg: '#181A20',
    card: '#21252D',
    layoutTags: ['Bento Grid', 'Minimal Edge', 'Sharp 0px', 'Monospace'],
  },
  {
    id: 'cyber-matrix',
    name: 'Cyberpunk Terminal 2077',
    badge: 'High-Tech Studio',
    category: 'cyber',
    desc: 'Split media showcase with neon matrix green, developer terminal font, floating island navigation, and glass card surfaces.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'mono',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'highlights', 'services', 'portfolio', 'results', 'about', 'blog', 'reviews', 'contact'],
    primary: '#00FF66',
    secondary: '#0D2818',
    accent: '#00E5FF',
    bg: '#050D08',
    card: '#0A1A10',
    layoutTags: ['Split 50/50', 'Floating Nav', 'Clean 6px', 'Terminal Mono'],
  },
  {
    id: 'tokyo-neon',
    name: 'Tokyo Night Syndicate',
    badge: 'Electric Cyber',
    category: 'cyber',
    desc: 'Electric neon magenta and cyan aesthetic, video streamer hero, organic pill borders, and avant-garde geometric headers.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'reviews', 'about', 'blog', 'contact'],
    primary: '#FF007F',
    secondary: '#2A0845',
    accent: '#00F0FF',
    bg: '#0A0518',
    card: '#140C2E',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Pill 20px', 'Syne Type'],
  },
  {
    id: 'monolith-slate',
    name: 'Monolith Carbon Enterprise',
    badge: 'Enterprise Blue',
    category: 'enterprise',
    desc: 'Authoritative deep carbon corporate presentation with centered typographic impact, sticky header, and bordered surfaces.',
    isLight: false,
    heroLayout: 'centered',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'results', 'services', 'highlights', 'about', 'portfolio', 'reviews', 'blog', 'contact'],
    primary: '#38BDF8',
    secondary: '#1E293B',
    accent: '#0284C7',
    bg: '#0F172A',
    card: '#1E293B',
    layoutTags: ['Centered Focus', 'Sticky Header', 'Sharp 0px', 'Bordered'],
  },
  {
    id: 'velvet-noir',
    name: 'Velvet Noir Atelier',
    badge: 'Haute Couture',
    category: 'luxury',
    desc: 'Editorial luxury layout with generous whitespace, subtle gold trim, minimal borderless header, and Playfair serif headers.',
    isLight: false,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#D4AF37',
    secondary: '#211D17',
    accent: '#F3E5AB',
    bg: '#0D0C0A',
    card: '#171512',
    layoutTags: ['Editorial Layout', 'Minimal Nav', 'Modern 12px', 'Serif Luxury'],
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis Kinetic',
    badge: 'Digital Lab',
    category: 'creative',
    desc: 'Bento grid layout with iridescent emerald-cyan gradients, floating island bar, and sleek modern card curvature.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#2DD4BF',
    secondary: '#132E2B',
    accent: '#38BDF8',
    bg: '#081716',
    card: '#0F2624',
    layoutTags: ['Bento Grid', 'Floating Island', 'Modern 12px', 'Syne Type'],
  },
  {
    id: 'deep-abyss',
    name: 'Deep Abyss Maritime',
    badge: 'Oceanic Tech',
    category: 'enterprise',
    desc: 'Deep marine navy aesthetic with streamer video backdrop, sticky navigation, clean borders, and elevated cards.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'services', 'portfolio', 'highlights', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#38BDF8',
    secondary: '#0C2D48',
    accent: '#145DA0',
    bg: '#051329',
    card: '#0D2137',
    layoutTags: ['Streamer Reel', 'Sticky Top', 'Clean 6px', 'Elevated Shadow'],
  },
  {
    id: 'titanium-stealth',
    name: 'Titanium Hardware Lab',
    badge: 'Precision Industrial',
    category: 'architectural',
    desc: 'Split 50/50 industrial blueprint layout with matte gunmetal surfaces, minimal top bar, and developer monospace fonts.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'highlights', 'services', 'results', 'portfolio', 'about', 'blog', 'reviews', 'contact'],
    primary: '#94A3B8',
    secondary: '#334155',
    accent: '#CBD5E1',
    bg: '#0F172A',
    card: '#1E293B',
    layoutTags: ['Split 50/50', 'Minimal Edge', 'Sharp 0px', 'Monospace'],
  },
  {
    id: 'champagne-dusk',
    name: 'Champagne Dusk Private',
    badge: 'Wealth & Advisory',
    category: 'luxury',
    desc: 'Editorial storytelling layout with warm champagne rose gold, floating island nav, and high-prestige typography.',
    isLight: false,
    heroLayout: 'editorial',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'about', 'portfolio', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#E0A96D',
    secondary: '#2C211A',
    accent: '#F5C79E',
    bg: '#140E0B',
    card: '#1F1713',
    layoutTags: ['Editorial Hero', 'Floating Island', 'Modern 12px', 'Serif Luxury'],
  },
  {
    id: 'hyper-orange',
    name: 'Hyper Sonic High-Velocity',
    badge: 'Growth Engine',
    category: 'performance',
    desc: 'Vibrant electric safety-orange performance layout with streamer reel, sticky top header, and high-impact metrics focus.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'results', 'portfolio', 'services', 'highlights', 'reviews', 'about', 'blog', 'contact'],
    primary: '#FF6B00',
    secondary: '#2D1605',
    accent: '#FFA34D',
    bg: '#120800',
    card: '#1F0F03',
    layoutTags: ['Streamer Reel', 'Sticky Top', 'Clean 6px', 'Elevated Shadow'],
  },
  {
    id: 'cosmic-amethyst',
    name: 'Cosmic Amethyst Space',
    badge: 'Next-Gen Web3',
    category: 'creative',
    desc: 'Deep galactic indigo with vibrant violet accents, bento interactive cards, floating island nav, and geometric typography.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#A855F7',
    secondary: '#2E1065',
    accent: '#C084FC',
    bg: '#0F0728',
    card: '#1A0D3D',
    layoutTags: ['Bento Grid', 'Floating Island', 'Modern 12px', 'Syne Geometric'],
  },
  {
    id: 'linear-dark',
    name: 'Linear Dark Studio OS',
    badge: 'Product OS',
    category: 'enterprise',
    desc: 'Deep slate minimalism with centered hero, minimal edge-to-edge nav, sharp razor geometry, and electric indigo data lines.',
    isLight: false,
    heroLayout: 'centered',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#5E6AD2',
    secondary: '#1A1C23',
    accent: '#828FFF',
    bg: '#0F1015',
    card: '#15171E',
    layoutTags: ['Centered Focus', 'Minimal Nav', 'Sharp 0px', 'Bordered'],
  },
  {
    id: 'supabase-emerald',
    name: 'Supabase Database Dev',
    badge: 'Developer Cloud',
    category: 'enterprise',
    desc: 'Pitch-black developer platform with 50/50 split media, sticky header, monospace typography, and neon emerald phosphor.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'highlights', 'services', 'results', 'portfolio', 'about', 'blog', 'reviews', 'contact'],
    primary: '#3ECF8E',
    secondary: '#1A2E24',
    accent: '#70E2B3',
    bg: '#121212',
    card: '#1C1C1C',
    layoutTags: ['Split 50/50', 'Sticky Top', 'Clean 6px', 'Terminal Mono'],
  },
  {
    id: 'vercel-black',
    name: 'Vercel Next Monolith',
    badge: 'Next.js Precision',
    category: 'architectural',
    desc: 'Absolute stark black canvas with pure white vectors, bento interactive cards, minimal nav, and architectural precision.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'blog', 'reviews', 'contact'],
    primary: '#FFFFFF',
    secondary: '#222222',
    accent: '#EAEAEA',
    bg: '#000000',
    card: '#0A0A0A',
    layoutTags: ['Bento Grid', 'Minimal Edge', 'Sharp 0px', 'Monochrome'],
  },
  {
    id: 'stripe-indigo',
    name: 'Stripe Global Payments',
    badge: 'Global Infrastructure',
    category: 'enterprise',
    desc: 'Prestigious deep navy indigo aesthetic, streamer video backdrop, floating island nav, and modern rounded cards.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#635BFF',
    secondary: '#0F1E36',
    accent: '#00D4FF',
    bg: '#0A2540',
    card: '#13335A',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Modern 12px', 'Glass Cards'],
  },
  {
    id: 'cloudflare-amber',
    name: 'Cloudflare Edge Security',
    badge: 'Edge Network',
    category: 'performance',
    desc: 'High-availability infrastructure layout with centered hero, sticky header, clean corners, and electric amber security lines.',
    isLight: false,
    heroLayout: 'centered',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'mono',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'results', 'services', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#F38020',
    secondary: '#2B1A0D',
    accent: '#FAAD3F',
    bg: '#141414',
    card: '#1F1F1F',
    layoutTags: ['Centered Focus', 'Sticky Header', 'Clean 6px', 'Elevated Shadow'],
  },
  {
    id: 'hologram-cyan',
    name: 'Holographic Cyber Lab',
    badge: 'Spatial Computing',
    category: 'cyber',
    desc: 'Futuristic spatial computing laboratory with bento cards, floating island nav, and laser-sharp cyan-violet optics.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#00F0FF',
    secondary: '#210B3B',
    accent: '#D946EF',
    bg: '#080514',
    card: '#120B29',
    layoutTags: ['Bento Grid', 'Floating Island', 'Modern 12px', 'Laser Cyan'],
  },
  {
    id: 'brutalist-carbon',
    name: 'Brutalist Raw Mono',
    badge: 'Neo-Brutalism',
    category: 'architectural',
    desc: 'Uncompromising neo-brutalist industrialism with 50/50 split media, sharp 0px razor borders, and high-contrast bone white.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'about', 'results', 'blog', 'reviews', 'contact'],
    primary: '#F0F0F0',
    secondary: '#262626',
    accent: '#CCCCCC',
    bg: '#0D0D0D',
    card: '#171717',
    layoutTags: ['Split 50/50', 'Minimal Nav', 'Sharp 0px', 'Raw Brutalist'],
  },
  {
    id: 'monaco-grand-cru',
    name: 'Monaco Grand Prix Racing',
    badge: 'Motorsport Heritage',
    category: 'luxury',
    desc: 'Elite British racing green with champagne gold trim, streamer video hero, floating island nav, and modern rounded surfaces.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'highlights', 'results', 'reviews', 'blog', 'contact'],
    primary: '#E2B874',
    secondary: '#0C2618',
    accent: '#22C55E',
    bg: '#07170E',
    card: '#0E291B',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Modern 12px', 'Racing Green'],
  },
  {
    id: 'milanese-espresso',
    name: 'Milanese Sartorial Atelier',
    badge: 'Italian Luxury',
    category: 'luxury',
    desc: 'Rich roasted espresso tones with warm linen cream, editorial layout, minimal nav, and Playfair Display serif headers.',
    isLight: false,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#E6D7C3',
    secondary: '#2E1E14',
    accent: '#D4A373',
    bg: '#140E0A',
    card: '#1F1610',
    layoutTags: ['Editorial Hero', 'Minimal Nav', 'Modern 12px', 'Serif Espresso'],
  },
  {
    id: 'kyoto-night',
    name: 'Kyoto Cherry Blossom Night',
    badge: 'Japanese Atelier',
    category: 'creative',
    desc: 'Deep midnight indigo with sakura petal pink glow, bento interactive cards, capsule pill curves, and Syne typography.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'reviews', 'results', 'blog', 'contact'],
    primary: '#FF758F',
    secondary: '#25152B',
    accent: '#FFA3B8',
    bg: '#0D0814',
    card: '#181024',
    layoutTags: ['Bento Grid', 'Floating Island', 'Pill 20px', 'Sakura Glow'],
  },
  {
    id: 'quantum-ai',
    name: 'Quantum AI Research Labs',
    badge: 'Deep Tech & AI',
    category: 'enterprise',
    desc: 'Technical deep research layout with 50/50 split media, sticky header, clean corners, and quantum violet-cyan coherence.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'highlights', 'services', 'results', 'portfolio', 'about', 'blog', 'reviews', 'contact'],
    primary: '#38BDF8',
    secondary: '#1F1A3A',
    accent: '#A855F7',
    bg: '#0B0A17',
    card: '#141226',
    layoutTags: ['Split 50/50', 'Sticky Top', 'Clean 6px', 'Quantum Violet'],
  },
  {
    id: 'nordic-noir',
    name: 'Nordic Fjord Cold Studio',
    badge: 'Scandinavian Noir',
    category: 'minimal',
    desc: 'Glacial silver on deep Nordic fjord waters, centered minimal hero, minimal edge-to-edge nav, and sharp razor borders.',
    isLight: false,
    heroLayout: 'centered',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'results', 'blog', 'reviews', 'contact'],
    primary: '#E2E8F0',
    secondary: '#1A2333',
    accent: '#60A5FA',
    bg: '#090D14',
    card: '#101622',
    layoutTags: ['Centered Focus', 'Minimal Nav', 'Sharp 0px', 'Glacial Silver'],
  },
  {
    id: 'stealth-fighter',
    name: 'Stealth Avionics HUD',
    badge: 'Aerospace & Defense',
    category: 'performance',
    desc: 'Radar HUD tactical green with carbon matte armor, streamer video reel, sticky top header, and sharp elevated surfaces.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'results', 'highlights', 'services', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#22C55E',
    secondary: '#112215',
    accent: '#4ADE80',
    bg: '#060B07',
    card: '#0C170E',
    layoutTags: ['Streamer Reel', 'Sticky Header', 'Sharp 0px', 'HUD Green'],
  },
  {
    id: 'golden-hour-noir',
    name: 'Golden Hour Horizon',
    badge: 'Cinema & Media',
    category: 'creative',
    desc: 'Cinematic sunset amber bronze with charcoal slate, editorial storytelling hero, floating island nav, and modern rounded cards.',
    isLight: false,
    heroLayout: 'editorial',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#F59E0B',
    secondary: '#2B1C10',
    accent: '#FCD34D',
    bg: '#0F0B08',
    card: '#1A130E',
    layoutTags: ['Editorial Hero', 'Floating Island', 'Modern 12px', 'Cinema Amber'],
  },

  // ── Light Themes (22 Presets) ────────────────────────────────────────────
  {
    id: 'titanium-light',
    name: 'Titanium Apple Light',
    badge: 'Clean Minimal',
    category: 'minimal',
    desc: 'Crisp architectural light mode with frosted glass cards, centered minimal hero, floating island nav, and Apple-grade precision.',
    isLight: true,
    heroLayout: 'centered',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'highlights', 'services', 'portfolio', 'results', 'about', 'blog', 'reviews', 'contact'],
    primary: '#0071E3',
    secondary: '#F2F2F7',
    accent: '#0071E3',
    bg: '#F5F5F7',
    card: '#FFFFFF',
    layoutTags: ['Centered Focus', 'Floating Island', 'Modern 12px', 'Apple Glass'],
  },
  {
    id: 'pure-minimal',
    name: 'Pure Minimalist Studio',
    badge: 'Architectural Light',
    category: 'architectural',
    desc: 'Black-and-white editorial restraint with 50/50 split media layout, minimal borderless nav, and sharp razor-edge cards.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'results', 'blog', 'reviews', 'contact'],
    primary: '#111113',
    secondary: '#F7F7F9',
    accent: '#0071E3',
    bg: '#FFFFFF',
    card: '#F7F7F9',
    layoutTags: ['Split 50/50', 'Minimal Edge', 'Sharp 0px', 'Monospace'],
  },
  {
    id: 'nordic-sky',
    name: 'Nordic Sky Clean SaaS',
    badge: 'Scandinavian Clean',
    category: 'enterprise',
    desc: 'Bright ice-blue Scandinavian enterprise layout with streamer reel, sticky top header, clean corners, and high legibility.',
    isLight: true,
    heroLayout: 'streamer',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#0284C7',
    secondary: '#F0F9FF',
    accent: '#0284C7',
    bg: '#F8FAFC',
    card: '#FFFFFF',
    layoutTags: ['Streamer Reel', 'Sticky Top', 'Clean 6px', 'Elevated Shadow'],
  },
  {
    id: 'editorial-ivory',
    name: 'Editorial Ivory Atelier',
    badge: 'Luxury Editorial',
    category: 'editorial',
    desc: 'Editorial layout with warm ivory background, minimal nav, Playfair Display serif headings, and refined boutique elegance.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#92400E',
    secondary: '#FEF3C7',
    accent: '#B45309',
    bg: '#FFFBEB',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Minimal Nav', 'Modern 12px', 'Serif Ivory'],
  },
  {
    id: 'swiss-clean',
    name: 'Swiss International Grid',
    badge: 'International Style',
    category: 'architectural',
    desc: 'Helvetica-inspired Swiss modernism with 50/50 split media, sharp 0px corners, minimal borderless header, and scarlet accents.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'results', 'about', 'blog', 'reviews', 'contact'],
    primary: '#DC2626',
    secondary: '#F5F5F5',
    accent: '#EF4444',
    bg: '#FFFFFF',
    card: '#FBFBFB',
    layoutTags: ['Split 50/50', 'Minimal Edge', 'Sharp 0px', 'Swiss Grid'],
  },
  {
    id: 'california-sunset',
    name: 'California Sunset Studio',
    badge: 'Warm Creative',
    category: 'creative',
    desc: 'Warm peach-amber tones with centered hero, floating capsule island nav, organic pill curves, and Syne geometric typography.',
    isLight: true,
    heroLayout: 'centered',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#EA580C',
    secondary: '#FFEDD5',
    accent: '#F97316',
    bg: '#FFF7ED',
    card: '#FFFFFF',
    layoutTags: ['Centered Focus', 'Floating Island', 'Pill 20px', 'Syne Geometric'],
  },
  {
    id: 'matcha-zen',
    name: 'Matcha Zen Botanical',
    badge: 'Organic Studio',
    category: 'creative',
    desc: 'Calming sage and matcha green palette, editorial storytelling hero, floating island nav, and modern rounded cards.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'about', 'portfolio', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#15803D',
    secondary: '#DCFCE7',
    accent: '#16A34A',
    bg: '#F0FDF4',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Floating Island', 'Modern 12px', 'Serif Botanical'],
  },
  {
    id: 'fintech-slate',
    name: 'Fintech Slate Blue Light',
    badge: 'Financial Services',
    category: 'enterprise',
    desc: 'Bank-grade credibility with split 50/50 showcase, sticky top navigation, clean industrial radius, and developer monospace accents.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'mono',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#0F172A',
    secondary: '#E2E8F0',
    accent: '#2563EB',
    bg: '#F8FAFC',
    card: '#FFFFFF',
    layoutTags: ['Split 50/50', 'Sticky Top', 'Clean 6px', 'Monospace'],
  },
  {
    id: 'rose-parisian',
    name: 'Rose Parisian Boutique',
    badge: 'Luxury Fashion',
    category: 'luxury',
    desc: 'Soft rose blush surfaces with centered typography, minimal header, modern rounded corners, and Playfair serif elegance.',
    isLight: true,
    heroLayout: 'centered',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#BE185D',
    secondary: '#FCE7F3',
    accent: '#DB2777',
    bg: '#FDF2F8',
    card: '#FFFFFF',
    layoutTags: ['Centered Focus', 'Minimal Nav', 'Modern 12px', 'Serif Rose'],
  },
  {
    id: 'coastal-breeze',
    name: 'Coastal Breeze Pacific',
    badge: 'Modern Agency',
    category: 'minimal',
    desc: 'Vibrant turquoise ocean clarity, streamer video hero, floating capsule bar, organic pill curvature, and system typography.',
    isLight: true,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#0D9488',
    secondary: '#CCFBF1',
    accent: '#14B8A6',
    bg: '#F0FDFA',
    card: '#FFFFFF',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Pill 20px', 'Clean Glass'],
  },
  {
    id: 'monochrome-paper',
    name: 'Monochrome Newsprint',
    badge: 'Literary Press',
    category: 'editorial',
    desc: 'High-contrast black-and-white broadsheet journalism layout with editorial hero, minimal nav, and sharp razor borders.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'playfair',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'blog', 'reviews', 'results', 'contact'],
    primary: '#000000',
    secondary: '#F3F4F6',
    accent: '#374151',
    bg: '#FFFFFF',
    card: '#FAFAFA',
    layoutTags: ['Editorial Hero', 'Minimal Nav', 'Sharp 0px', 'Serif Broadside'],
  },
  {
    id: 'solar-apricot',
    name: 'Solar Apricot Creative',
    badge: 'Digital Commerce',
    category: 'creative',
    desc: 'Golden amber sunrise palette with bento layout, floating island bar, clean corners, and Syne geometric typography.',
    isLight: true,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'elevated',
    fontFamily: 'syne',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#D97706',
    secondary: '#FEF3C7',
    accent: '#F59E0B',
    bg: '#FFFDF5',
    card: '#FFFFFF',
    layoutTags: ['Bento Grid', 'Floating Island', 'Clean 6px', 'Syne Geometric'],
  },
  {
    id: 'stripe-clean-light',
    name: 'Stripe Press Financial Light',
    badge: 'Fintech SaaS',
    category: 'enterprise',
    desc: 'Brisk international fintech presentation with 50/50 split media, sticky header, clean corners, and royal electric indigo lines.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'elevated',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#635BFF',
    secondary: '#F4F5F9',
    accent: '#00D4FF',
    bg: '#FAFAFA',
    card: '#FFFFFF',
    layoutTags: ['Split 50/50', 'Sticky Top', 'Clean 6px', 'Stripe Indigo'],
  },
  {
    id: 'scandinavian-birch',
    name: 'Scandinavian Birch Minimal',
    badge: 'Nordic Woodcraft',
    category: 'minimal',
    desc: 'Warm organic Nordic minimalism with centered focus hero, minimal edge-to-edge nav, modern rounded cards, and honey birch trim.',
    isLight: true,
    heroLayout: 'centered',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'results', 'blog', 'reviews', 'contact'],
    primary: '#B45309',
    secondary: '#F5EBE1',
    accent: '#D97706',
    bg: '#FDFCFB',
    card: '#FFFFFF',
    layoutTags: ['Centered Focus', 'Minimal Nav', 'Modern 12px', 'Birch Wood'],
  },
  {
    id: 'bauhaus-modern',
    name: 'Bauhaus Primary Atelier',
    badge: 'Art Modernism',
    category: 'creative',
    desc: 'Iconic modernism with bento geometric grid, minimal nav, razor sharp 0px borders, and saturated cobalt-canary highlights.',
    isLight: true,
    heroLayout: 'bento',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'syne',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#1D4ED8',
    secondary: '#FEF08A',
    accent: '#EAB308',
    bg: '#FFFFFF',
    card: '#F8FAFC',
    layoutTags: ['Bento Grid', 'Minimal Edge', 'Sharp 0px', 'Bauhaus Grid'],
  },
  {
    id: 'harvard-crimson',
    name: 'Harvard Crimson Academic Press',
    badge: 'Academic Heritage',
    category: 'editorial',
    desc: 'Prestige university press style with editorial hero, minimal nav, sharp 0px corners, and deep crimson on parchment.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'playfair',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'about', 'portfolio', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#991B1B',
    secondary: '#FEE2E2',
    accent: '#DC2626',
    bg: '#FDFBF7',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Minimal Nav', 'Sharp 0px', 'Academic Crimson'],
  },
  {
    id: 'tokyo-ginza',
    name: 'Tokyo Ginza High-Street Clean',
    badge: 'Tokyo Minimal',
    category: 'luxury',
    desc: 'High-fashion Ginza commercial strip layout with 50/50 split media, floating island bar, vermillion red, and Syne typography.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#E11D48',
    secondary: '#FFE4E6',
    accent: '#F43F5E',
    bg: '#F8F9FA',
    card: '#FFFFFF',
    layoutTags: ['Split 50/50', 'Floating Island', 'Clean 6px', 'Ginza Red'],
  },
  {
    id: 'mediterranean-azure',
    name: 'Mediterranean Azure Coast',
    badge: 'Resort & Marine',
    category: 'minimal',
    desc: 'Sun-drenched Mediterranean blue clarity with streamer video hero, floating capsule pill nav, and luminous glass cards.',
    isLight: true,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'highlights', 'portfolio', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#0284C7',
    secondary: '#E0F2FE',
    accent: '#0EA5E9',
    bg: '#F0F9FF',
    card: '#FFFFFF',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Pill 20px', 'Azure Coast'],
  },
  {
    id: 'monocle-magazine',
    name: 'Monocle Global Dispatch',
    badge: 'Global Journalism',
    category: 'editorial',
    desc: 'Cosmopolitan dispatch aesthetic with editorial storytelling layout, minimal nav, British racing hunter green on soft vanilla.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'reviews', 'highlights', 'results', 'blog', 'contact'],
    primary: '#166534',
    secondary: '#DCFCE7',
    accent: '#15803D',
    bg: '#FDF8F0',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Minimal Nav', 'Modern 12px', 'Serif Monocle'],
  },
  {
    id: 'linear-light-craft',
    name: 'Linear Light Precision Craft',
    badge: 'Developer Tools',
    category: 'enterprise',
    desc: 'Electric purple developer tools aesthetic with centered focus hero, sticky top header, sharp razor borders, and monospace font.',
    isLight: true,
    heroLayout: 'centered',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'services', 'results', 'highlights', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#7C3AED',
    secondary: '#EDE9FE',
    accent: '#8B5CF6',
    bg: '#F8FAFC',
    card: '#FFFFFF',
    layoutTags: ['Centered Focus', 'Sticky Header', 'Sharp 0px', 'Terminal Violet'],
  },
  {
    id: 'apothecary-sage',
    name: 'Herbal Apothecary Sage',
    badge: 'Botanical Luxury',
    category: 'creative',
    desc: 'Restorative herbal apothecary tones with editorial hero, floating capsule island nav, pill curves, and Playfair serif headers.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'about', 'portfolio', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#059669',
    secondary: '#D1FAE5',
    accent: '#10B981',
    bg: '#F0FDF4',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Floating Island', 'Pill 20px', 'Apothecary Sage'],
  },
  {
    id: 'santorini-cliff',
    name: 'Santorini Cliffside White',
    badge: 'Cycladic Architecture',
    category: 'architectural',
    desc: 'Pure Cycladic whitewash with deep Aegean blue accents, 50/50 split media, floating island bar, and modern rounded cards.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#0369A1',
    secondary: '#E0F2FE',
    accent: '#0284C7',
    bg: '#FFFFFF',
    card: '#F8FAFC',
    layoutTags: ['Split 50/50', 'Floating Island', 'Modern 12px', 'Aegean Blue'],
  },

  // ── Additional Curated Dark Themes ──
  {
    id: 'monolith-brutalist',
    name: 'Monolith Architectural Noir',
    badge: 'Brutalist Concrete',
    category: 'architectural',
    desc: 'Heavy architectural concrete aesthetic with centered hero focus, sharp razor edges, sticky header, and silver-grey geometry.',
    isLight: false,
    heroLayout: 'centered',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'services', 'highlights', 'about', 'results', 'blog', 'reviews', 'contact'],
    primary: '#CBD5E1',
    secondary: '#1A202C',
    accent: '#94A3B8',
    bg: '#0F1217',
    card: '#181E26',
    layoutTags: ['Centered Focus', 'Sticky Header', 'Sharp 0px', 'Brutalist Concrete'],
  },
  {
    id: 'bioluminescent-deep',
    name: 'Bioluminescent Abyss Tech',
    badge: 'Deep Sea AI',
    category: 'creative',
    desc: 'Deep Mariana oceanic trench dark with bioluminescent emerald-cyan glow, bento grid layout, pill curves, and Syne typography.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'reviews', 'results', 'blog', 'contact'],
    primary: '#00F5D4',
    secondary: '#07242B',
    accent: '#7B2CBF',
    bg: '#020C10',
    card: '#06171E',
    layoutTags: ['Bento Grid', 'Floating Island', 'Pill 20px', 'Bioluminescent Cyan'],
  },
  {
    id: 'hyper-car-red',
    name: 'Hypercar Kinetic Aerodynamics',
    badge: 'Motorsport & Luxury',
    category: 'performance',
    desc: 'Rosso Corsa scarlet velocity on carbon fiber weave, cinematic streamer reel, floating island bar, and clean precision radii.',
    isLight: false,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'elevated',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'results', 'highlights', 'services', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#EF4444',
    secondary: '#200A0A',
    accent: '#F87171',
    bg: '#0B0505',
    card: '#160B0B',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Clean 6px', 'Rosso Corsa'],
  },
  {
    id: 'astrophysics-gold',
    name: 'Astrophysics Celestial Gold',
    badge: 'Deep Space Atelier',
    category: 'luxury',
    desc: 'Deep galactic nebula plum with radiant solar gold highlights, editorial storytelling hero, floating island nav, and serif typography.',
    isLight: false,
    heroLayout: 'editorial',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'about', 'portfolio', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#FBBF24',
    secondary: '#241433',
    accent: '#FDE68A',
    bg: '#0E0716',
    card: '#1A0F27',
    layoutTags: ['Editorial Hero', 'Floating Island', 'Modern 12px', 'Celestial Gold'],
  },
  {
    id: 'matrix-overclocked',
    name: 'Phosphor Green Terminal',
    badge: 'DevOps & Systems',
    category: 'cyber',
    desc: 'High-contrast CRT phosphor green on deep matte obsidian, split media layout, sticky top header, and sharp borders.',
    isLight: false,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'mono',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'services', 'highlights', 'results', 'portfolio', 'about', 'blog', 'reviews', 'contact'],
    primary: '#10B981',
    secondary: '#062817',
    accent: '#34D399',
    bg: '#040E08',
    card: '#0A1E12',
    layoutTags: ['Split 50/50', 'Sticky Top', 'Sharp 0px', 'Phosphor Green'],
  },
  {
    id: 'tokyo-rain',
    name: 'Shinjuku Neon Rain',
    badge: 'Cyberpunk Aesthetic',
    category: 'creative',
    desc: 'Drenched Shinjuku midnight asphalt with blazing hot magenta and electric violet neon, bento grid, and modern curves.',
    isLight: false,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'results', 'about', 'reviews', 'blog', 'contact'],
    primary: '#EC4899',
    secondary: '#280A22',
    accent: '#8B5CF6',
    bg: '#0C040E',
    card: '#190A1C',
    layoutTags: ['Bento Grid', 'Floating Island', 'Modern 12px', 'Hot Magenta'],
  },

  // ── Additional Curated Light Themes ──
  {
    id: 'atelier-porcelain',
    name: 'Parisian Porcelain Atelier',
    badge: 'Haute Horlogerie',
    category: 'luxury',
    desc: 'Warm French porcelain ivory with antique bronze accents, editorial storytelling hero, floating island nav, and Playfair serif.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'about', 'portfolio', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#B45309',
    secondary: '#FEF3C7',
    accent: '#D97706',
    bg: '#FDFBF7',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Floating Island', 'Pill 20px', 'Antique Bronze'],
  },
  {
    id: 'bauhaus-minimal',
    name: 'Bauhaus Architectural Clean',
    badge: 'German Modernism',
    category: 'architectural',
    desc: 'Pure German Bauhaus minimalism with cobalt blue primary geometry, 50/50 split media, sticky header, and sharp crisp corners.',
    isLight: true,
    heroLayout: 'split',
    headerStyle: 'sticky',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'sharp',
    sectionsOrder: ['hero', 'portfolio', 'services', 'highlights', 'results', 'about', 'blog', 'reviews', 'contact'],
    primary: '#1D4ED8',
    secondary: '#EFF6FF',
    accent: '#2563EB',
    bg: '#FAFAFA',
    card: '#FFFFFF',
    layoutTags: ['Split 50/50', 'Sticky Header', 'Sharp 0px', 'Cobalt Bauhaus'],
  },
  {
    id: 'nordic-paper',
    name: 'Nordic Paper & Forest Moss',
    badge: 'Copenhagen Design',
    category: 'minimal',
    desc: 'Unbleached natural Nordic craft paper with deep forest moss green, centered hero focus, minimal nav, and clean 6px radii.',
    isLight: true,
    heroLayout: 'centered',
    headerStyle: 'minimal',
    cardStyle: 'bordered',
    fontFamily: 'system',
    borderRadius: 'clean',
    sectionsOrder: ['hero', 'about', 'services', 'portfolio', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#15803D',
    secondary: '#F0FDF4',
    accent: '#16A34A',
    bg: '#FAF8F5',
    card: '#FFFFFF',
    layoutTags: ['Centered Focus', 'Minimal Nav', 'Clean 6px', 'Forest Moss'],
  },
  {
    id: 'solaris-cream',
    name: 'Solaris Mediterranean Cream',
    badge: 'Riviera Resort',
    category: 'creative',
    desc: 'Sun-warmed terracotta orange on Riviera clifftop cream, cinematic streamer video reel, floating island bar, and serif elegance.',
    isLight: true,
    heroLayout: 'streamer',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'playfair',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'portfolio', 'highlights', 'services', 'about', 'reviews', 'results', 'blog', 'contact'],
    primary: '#EA580C',
    secondary: '#FFEDD5',
    accent: '#F97316',
    bg: '#FFFDF9',
    card: '#FFFFFF',
    layoutTags: ['Streamer Reel', 'Floating Island', 'Modern 12px', 'Terracotta Orange'],
  },
  {
    id: 'apple-pro-white',
    name: 'Cupertino Studio Glass',
    badge: 'Pro Hardware & Software',
    category: 'enterprise',
    desc: 'Ultra-refined Cupertino frosted glass with electric sapphire accents, bento interactive grid, floating capsule nav, and system font.',
    isLight: true,
    heroLayout: 'bento',
    headerStyle: 'floating',
    cardStyle: 'glass',
    fontFamily: 'system',
    borderRadius: 'modern',
    sectionsOrder: ['hero', 'highlights', 'services', 'results', 'portfolio', 'about', 'reviews', 'blog', 'contact'],
    primary: '#0071E3',
    secondary: '#F2F2F7',
    accent: '#2997FF',
    bg: '#F5F5F7',
    card: '#FFFFFF',
    layoutTags: ['Bento Grid', 'Floating Island', 'Modern 12px', 'Sapphire Glass'],
  },
  {
    id: 'tokyo-spring-light',
    name: 'Tokyo Cherry Blossom Dawn',
    badge: 'Japanese Contemporary',
    category: 'creative',
    desc: 'Morning sunlight on sakura blossoms with soft rose quartz accents, editorial storytelling hero, minimal nav, and pill radii.',
    isLight: true,
    heroLayout: 'editorial',
    headerStyle: 'minimal',
    cardStyle: 'glass',
    fontFamily: 'syne',
    borderRadius: 'pill',
    sectionsOrder: ['hero', 'portfolio', 'about', 'services', 'highlights', 'reviews', 'results', 'blog', 'contact'],
    primary: '#E11D48',
    secondary: '#FFF1F2',
    accent: '#FB7185',
    bg: '#FFFBFB',
    card: '#FFFFFF',
    layoutTags: ['Editorial Hero', 'Minimal Nav', 'Pill 20px', 'Sakura Rose'],
  },
];

// ── Curated Professional Color Palettes (40+ Palettes inspired by Coolors) ──
export const COLOR_PALETTES = [
  // ── Dark & Stealth (14 Palettes) ──────────────────────────────────────────
  {
    id: 'pal-codex-gold',
    name: 'Codex Gold Stealth',
    category: 'dark',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#F0B90B',
    bg: '#0F1216',
    card: '#181A20',
    accent: '#FCD535',
    secondary: '#1E2329',
    tags: ['Binance Pro', 'Luxury Gold', 'Stealth'],
  },
  {
    id: 'pal-pacific-blue',
    name: 'Pacific Electric Blue',
    category: 'ocean',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#2979F0',
    bg: '#0B111A',
    card: '#121D2C',
    accent: '#00D2FF',
    secondary: '#162235',
    tags: ['SaaS Tech', 'Cyan Glow', 'Enterprise'],
  },
  {
    id: 'pal-emerald-peak',
    name: 'Emerald Peak Matrix',
    category: 'nature',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#0ECB81',
    bg: '#0A1510',
    card: '#10221A',
    accent: '#26E69D',
    secondary: '#132820',
    tags: ['Botanical Dark', 'Mint Neon', 'Finance'],
  },
  {
    id: 'pal-royal-violet',
    name: 'Royal Amethyst Violet',
    category: 'luxury',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#8B5CF6',
    bg: '#100C1B',
    card: '#1A142D',
    accent: '#A78BFA',
    secondary: '#241B3B',
    tags: ['Haute Luxury', 'Purple Glow', 'Editorial'],
  },
  {
    id: 'pal-crimson-kinetic',
    name: 'Crimson Kinetic Scarlet',
    category: 'warm',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#F6465D',
    bg: '#16090D',
    card: '#240F15',
    accent: '#FF6B81',
    secondary: '#2E151B',
    tags: ['Performance', 'Scarlet Energy', 'High-ROAS'],
  },
  {
    id: 'pal-dark-obsidian',
    name: 'Dark Obsidian Monolith',
    category: 'dark',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#EAECEF',
    bg: '#181A20',
    card: '#21252D',
    accent: '#F0B90B',
    secondary: '#2B313A',
    tags: ['Architectural', 'Gunmetal', 'Monochrome'],
  },
  {
    id: 'pal-cyber-terminal',
    name: 'Terminal 2077 Green',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#00FF66',
    bg: '#050D08',
    card: '#0A1A10',
    accent: '#00E5FF',
    secondary: '#0D2818',
    tags: ['Cyberpunk', 'Hacker Terminal', 'Neon'],
  },
  {
    id: 'pal-tokyo-synth',
    name: 'Tokyo Synthwave Magenta',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#FF007F',
    bg: '#0A0518',
    card: '#140C2E',
    accent: '#00F0FF',
    secondary: '#2A0845',
    tags: ['Synthwave', 'Neon Magenta', 'Cyan Edge'],
  },
  {
    id: 'pal-deep-navy-carbon',
    name: 'Carbon Deep Space',
    category: 'ocean',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#38BDF8',
    bg: '#0B0F19',
    card: '#111827',
    accent: '#60A5FA',
    secondary: '#1F2937',
    tags: ['Starlight Navy', 'Enterprise', 'Executive'],
  },
  {
    id: 'pal-hyper-amber',
    name: 'Hyper Sonic Safety Orange',
    category: 'warm',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#FF6B00',
    bg: '#120800',
    card: '#1F0F03',
    accent: '#FFA34D',
    secondary: '#2D1605',
    tags: ['Safety Orange', 'Dynamic', 'High-Impact'],
  },
  {
    id: 'pal-titanium-slate',
    name: 'Titanium Hardware Stealth',
    category: 'dark',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#94A3B8',
    bg: '#0F172A',
    card: '#1E293B',
    accent: '#38BDF8',
    secondary: '#334155',
    tags: ['Hardware Precision', 'Matte Slate', 'Industrial'],
  },
  {
    id: 'pal-champagne-noir',
    name: 'Champagne Noir Gold',
    category: 'luxury',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#D4AF37',
    bg: '#0D0C0A',
    card: '#171512',
    accent: '#F3E5AB',
    secondary: '#211D17',
    tags: ['Private Reserve', '24k Gold', 'Haute Couture'],
  },
  {
    id: 'pal-abyss-teal',
    name: 'Abyss Bioluminescent Teal',
    category: 'nature',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#14B8A6',
    bg: '#041618',
    card: '#082529',
    accent: '#2DD4BF',
    secondary: '#0C353B',
    tags: ['Deep Ocean', 'Bioluminescence', 'Marine'],
  },
  {
    id: 'pal-solar-crimson',
    name: 'Solar Flare Sunset',
    category: 'warm',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#F97316',
    bg: '#180B05',
    card: '#29140B',
    accent: '#FBBF24',
    secondary: '#381C0E',
    tags: ['Solar Flare', 'Amber Glow', 'Dynamic'],
  },

  // ── Clean Light (14 Palettes) ─────────────────────────────────────────────
  {
    id: 'pal-titanium-light',
    name: 'Apple Titanium Light',
    category: 'light',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#0071E3',
    bg: '#F5F5F7',
    card: '#FFFFFF',
    accent: '#0071E3',
    secondary: '#F2F2F7',
    tags: ['Cupertino Clean', 'Apple Blueprint', 'Sleek'],
  },
  {
    id: 'pal-pure-minimal',
    name: 'Pure Minimal Studio',
    category: 'light',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#111113',
    bg: '#FFFFFF',
    card: '#F7F7F9',
    accent: '#0071E3',
    secondary: '#EAEAEC',
    tags: ['Black & White', 'Architectural', 'Razor'],
  },
  {
    id: 'pal-nordic-sky',
    name: 'Nordic Ice Sky',
    category: 'ocean',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#0284C7',
    bg: '#F8FAFC',
    card: '#FFFFFF',
    accent: '#0284C7',
    secondary: '#F0F9FF',
    tags: ['Scandinavian', 'Ice Blue', 'SaaS Clean'],
  },
  {
    id: 'pal-editorial-ivory',
    name: 'Editorial Cream Ivory',
    category: 'luxury',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#92400E',
    bg: '#FFFBEB',
    card: '#FFFFFF',
    accent: '#B45309',
    secondary: '#FEF3C7',
    tags: ['Warm Ivory', 'Serif Press', 'Boutique'],
  },
  {
    id: 'pal-swiss-red',
    name: 'Swiss Modernist Red',
    category: 'warm',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#DC2626',
    bg: '#FFFFFF',
    card: '#FBFBFB',
    accent: '#EF4444',
    secondary: '#F5F5F5',
    tags: ['Helvetica Grid', 'Swiss Scarlet', 'Poster'],
  },
  {
    id: 'pal-matcha-botanical',
    name: 'Matcha Sage Botanical',
    category: 'nature',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#15803D',
    bg: '#F0FDF4',
    card: '#FFFFFF',
    accent: '#16A34A',
    secondary: '#DCFCE7',
    tags: ['Organic Wellness', 'Sage Clean', 'Fresh'],
  },
  {
    id: 'pal-california-peach',
    name: 'California Peach Sunset',
    category: 'warm',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#EA580C',
    bg: '#FFF7ED',
    card: '#FFFFFF',
    accent: '#F97316',
    secondary: '#FFEDD5',
    tags: ['Golden Hour', 'Warm Apricot', 'Creative'],
  },
  {
    id: 'pal-fintech-cobalt',
    name: 'Wall Street Slate Cobalt',
    category: 'ocean',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#0F172A',
    bg: '#F8FAFC',
    card: '#FFFFFF',
    accent: '#2563EB',
    secondary: '#E2E8F0',
    tags: ['Bank Credibility', 'Slate Charcoal', 'Fintech'],
  },
  {
    id: 'pal-rose-parisian',
    name: 'Rose Parisian Blush',
    category: 'luxury',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#BE185D',
    bg: '#FDF2F8',
    card: '#FFFFFF',
    accent: '#DB2777',
    secondary: '#FCE7F3',
    tags: ['High Fashion', 'Blush Velvet', 'Atelier'],
  },
  {
    id: 'pal-coastal-lagoon',
    name: 'Pacific Coastal Lagoon',
    category: 'nature',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#0D9488',
    bg: '#F0FDFA',
    card: '#FFFFFF',
    accent: '#14B8A6',
    secondary: '#CCFBF1',
    tags: ['Turquoise Sea', 'Lagoon Clarity', 'Modern'],
  },
  {
    id: 'pal-lavender-mist',
    name: 'Lavender Mist Studio',
    category: 'luxury',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#7C3AED',
    bg: '#FAF5FF',
    card: '#FFFFFF',
    accent: '#8B5CF6',
    secondary: '#F3E8FF',
    tags: ['Pastel Violet', 'Creative Studio', 'Soft'],
  },
  {
    id: 'pal-solar-amber',
    name: 'Solar Honey Amber',
    category: 'warm',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#D97706',
    bg: '#FFFDF5',
    card: '#FFFFFF',
    accent: '#F59E0B',
    secondary: '#FEF3C7',
    tags: ['Golden Honey', 'Warm Sunlight', 'Friendly'],
  },
  {
    id: 'pal-monochrome-slate',
    name: 'Monochrome Cool Slate',
    category: 'light',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#334155',
    bg: '#F1F5F9',
    card: '#FFFFFF',
    accent: '#475569',
    secondary: '#E2E8F0',
    tags: ['Industrial Slate', 'Technical', 'Minimal'],
  },
  {
    id: 'pal-emerald-clean',
    name: 'Clover Clean Emerald',
    category: 'nature',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#047857',
    bg: '#ECFDF5',
    card: '#FFFFFF',
    accent: '#059669',
    secondary: '#D1FAE5',
    tags: ['Vibrant Green', 'E-Commerce', 'High Trust'],
  },

  // ── High-Contrast & Cyber/Neon (12 Palettes) ──────────────────────────────
  {
    id: 'pal-hyper-neon-yellow',
    name: 'Cyberpunk Hazard Yellow',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#FFE600',
    bg: '#0A0A00',
    card: '#141400',
    accent: '#FFF066',
    secondary: '#222200',
    tags: ['Hazard Warning', 'High-Volt', 'Cyberpunk'],
  },
  {
    id: 'pal-hyper-cyan-matrix',
    name: 'Neon Cyan Overdrive',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#00F5FF',
    bg: '#030E14',
    card: '#061924',
    accent: '#66FAFF',
    secondary: '#0C2A3C',
    tags: ['Tron Cyan', 'High Velocity', 'Electric'],
  },
  {
    id: 'pal-toxic-lime',
    name: 'Toxic Lime Acid',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#A3E635',
    bg: '#0A1203',
    card: '#132107',
    accent: '#BEF264',
    secondary: '#1C310A',
    tags: ['Acid Lime', 'Gen-Z Energy', 'Bold'],
  },
  {
    id: 'pal-vaporwave-sunset',
    name: 'Vaporwave Sunset Gradient',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#FF2A85',
    bg: '#11052C',
    card: '#1B0842',
    accent: '#00F0FF',
    secondary: '#2B0E68',
    tags: ['Retro Wave', 'Hot Pink', 'Electric Blue'],
  },
  {
    id: 'pal-ultraviolet-deep',
    name: 'Ultraviolet Dark Matter',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#6366F1',
    bg: '#0B0B1E',
    card: '#131336',
    accent: '#818CF8',
    secondary: '#1C1C4E',
    tags: ['Deep Space', 'Indigo Plasma', 'Web3'],
  },
  {
    id: 'pal-bronze-patina',
    name: 'Ancient Bronze Patina',
    category: 'luxury',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#C29B38',
    bg: '#14120C',
    card: '#1F1C13',
    accent: '#38A169',
    secondary: '#2B271A',
    tags: ['Patina Bronze', 'Antiquity', 'Luxury Heritage'],
  },
  {
    id: 'pal-copper-forge',
    name: 'Molten Copper Forge',
    category: 'warm',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#FB923C',
    bg: '#1A0C05',
    card: '#291409',
    accent: '#FDBA74',
    secondary: '#3B1F0F',
    tags: ['Molten Metal', 'Warm Industrial', 'Forged'],
  },
  {
    id: 'pal-glacier-mint',
    name: 'Glacier Mint Crisp',
    category: 'nature',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#059669',
    bg: '#F2FBF7',
    card: '#FFFFFF',
    accent: '#10B981',
    secondary: '#D1FAE5',
    tags: ['Alpine Air', 'Glacial Mint', 'Pristine'],
  },
  {
    id: 'pal-barcelona-terracotta',
    name: 'Barcelona Terracotta',
    category: 'warm',
    isLight: true,
    contrastLevel: 'AAA',
    primary: '#C2410C',
    bg: '#FFF8F4',
    card: '#FFFFFF',
    accent: '#EA580C',
    secondary: '#FFEDD5',
    tags: ['Mediterranean', 'Warm Clay', 'Artisanal'],
  },
  {
    id: 'pal-kyiv-chestnut',
    name: 'Kyiv Chestnut Gold',
    category: 'luxury',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#FFD700',
    bg: '#0E1117',
    card: '#161B22',
    accent: '#4182C4',
    secondary: '#21262D',
    tags: ['Kyiv Studio', 'Golden Dome', 'Blue Accent'],
  },
  {
    id: 'pal-monaco-casino',
    name: 'Monaco Grand Cru',
    category: 'luxury',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#E2B874',
    bg: '#0F1412',
    card: '#17201D',
    accent: '#28A745',
    secondary: '#202C28',
    tags: ['Bespoke Velvet', 'Racing Green', 'Casino Gold'],
  },
  {
    id: 'pal-quantum-electric',
    name: 'Quantum Superconductor',
    category: 'cyber',
    isLight: false,
    contrastLevel: 'AAA',
    primary: '#38BDF8',
    bg: '#030712',
    card: '#0B132B',
    accent: '#F43F5E',
    secondary: '#1C2541',
    tags: ['Quantum Core', 'Superconductor', 'Deep Void'],
  },
];

// Helper to determine luminance
export function getLuminance(hex) {
  if (!hex || typeof hex !== 'string') return 0;
  const clean = hex.replace('#', '').trim();
  if (clean.length !== 3 && clean.length !== 6) return 0;
  const r = parseInt(clean.length === 3 ? clean[0] + clean[0] : clean.substring(0, 2), 16);
  const g = parseInt(clean.length === 3 ? clean[1] + clean[1] : clean.substring(2, 4), 16);
  const b = parseInt(clean.length === 3 ? clean[2] + clean[2] : clean.substring(4, 6), 16);
  if (isNaN(r) || isNaN(g) || isNaN(b)) return 0;
  return (r * 299 + g * 587 + b * 114) / 1000;
}

export function isDarkHexCode(hex) {
  return getLuminance(hex) < 135;
}

// Coolors-style Dynamic Random Palette Generator
// Produces mathematically harmonious, professional palettes on the fly
const RANDOM_SEEDS = [
  // Dark Cyber / Tech
  {
    name: 'Cyberpunk Neon Genesis',
    isLight: false,
    primaries: ['#00FF88', '#00E5FF', '#FF0077', '#FFEA00', '#7928CA', '#22D3EE'],
    bgs: ['#050B14', '#080C16', '#090A10', '#070C09', '#0E071A', '#060B12'],
    cards: ['#0E1726', '#12192B', '#131522', '#0E1A14', '#1A0E2E', '#0D1B2A'],
  },
  // Dark Luxury Gold / Bronze
  {
    name: 'Imperial Reserve Gold',
    isLight: false,
    primaries: ['#F0B90B', '#E5A93C', '#D4AF37', '#FFD700', '#F59E0B', '#E0A96D'],
    bgs: ['#0C0E12', '#0F1014', '#120F0D', '#0F1216', '#14120C', '#101014'],
    cards: ['#161A22', '#181A20', '#1C1814', '#1B1E26', '#1E1B13', '#1B1C22'],
  },
  // Clean Apple / Titanium Light
  {
    name: 'Cupertino Executive Light',
    isLight: true,
    primaries: ['#0071E3', '#0284C7', '#2563EB', '#0F172A', '#0D9488', '#4F46E5'],
    bgs: ['#F5F5F7', '#F8FAFC', '#F0F9FF', '#FFFFFF', '#F1F5F9', '#FAFAFA'],
    cards: ['#FFFFFF', '#FFFFFF', '#FFFFFF', '#F8FAFC', '#FFFFFF', '#F8F9FA'],
  },
  // Clean Warm Editorial Light
  {
    name: 'Atelier Newsprint Ivory',
    isLight: true,
    primaries: ['#B45309', '#92400E', '#BE185D', '#C2410C', '#15803D', '#111113'],
    bgs: ['#FFFBEB', '#FFF7ED', '#FDF2F8', '#F0FDF4', '#FFFDF5', '#FAFAF9'],
    cards: ['#FFFFFF', '#FFFFFF', '#FFFFFF', '#FFFFFF', '#FFFFFF', '#FFFFFF'],
  },
  // Oceanic Deep
  {
    name: 'Pacific Mariana Abyss',
    isLight: false,
    primaries: ['#38BDF8', '#00D2FF', '#2DD4BF', '#60A5FA', '#818CF8', '#14B8A6'],
    bgs: ['#040D1A', '#020C17', '#06131F', '#071626', '#091524', '#051120'],
    cards: ['#0A192F', '#081D33', '#0E2338', '#102A43', '#12253B', '#0D2138'],
  },
];

export function generateRandomHarmoniousPalette(forceThemeMode = null) {
  let eligibleSeeds = RANDOM_SEEDS;
  if (forceThemeMode === 'light') {
    eligibleSeeds = RANDOM_SEEDS.filter(s => s.isLight);
  } else if (forceThemeMode === 'dark') {
    eligibleSeeds = RANDOM_SEEDS.filter(s => !s.isLight);
  }

  const seed = eligibleSeeds[Math.floor(Math.random() * eligibleSeeds.length)];
  const primary = seed.primaries[Math.floor(Math.random() * seed.primaries.length)];
  const bg = seed.bgs[Math.floor(Math.random() * seed.bgs.length)];
  const card = seed.cards[Math.floor(Math.random() * seed.cards.length)];
  
  // Pick complementary or harmonious accent
  const accentPool = seed.primaries.filter(p => p !== primary);
  const accent = accentPool.length > 0 ? accentPool[Math.floor(Math.random() * accentPool.length)] : primary;

  // Secondary tone
  const secondary = seed.isLight ? '#E5E7EB' : '#2B313A';

  const randomNum = Math.floor(100 + Math.random() * 900);
  return {
    id: `dynamic-${Date.now()}-${randomNum}`,
    name: `${seed.name} #${randomNum}`,
    category: seed.isLight ? 'light' : 'cyber',
    isLight: seed.isLight,
    contrastLevel: 'AAA',
    primary,
    bg,
    card,
    accent,
    secondary,
    tags: ['Coolors Generated', seed.isLight ? 'Apple Light' : 'Stealth Dark', 'Harmonious']
  };
}
